version: '3.8'

services:
  catch-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catch-api-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms128m -Xmx256m
    env_file:
      - .env
    depends_on:
      - catch-redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 450M # API 컨테이너가 450MB 이상 먹지 못하도록 물리적 제한

  catch-redis:
    image: redis:alpine
    container_name: catch-redis-prod
    expose:
      - "6379"
    restart: always
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru # Redis 메모리 최대 100MB 제한
    deploy:
      resources:
        limits:
          memory: 150M